public class KYCWrapper {
	public String requestId;	//299b8bd0-49c5-4da4-8e76-2e96a706045a
	public cls_result result;
	public Integer statusCode;	//101
	public String description;	//Valid Authentication
	public class cls_result {
        public String rcManuMonthYr;	//2011
		public String rcMakerModel;	//SANTRO GL
		public String rcFName;	//
		public String rcEngNo;	//G4HGBM194771
		public String rcOwnerName;	//SUMIT MEHTA
		public String rcVhClassDesc;	//MOTOR CAR
		public String rcPresentAddress;	//
		public String rcColor;	//D GREY MET
		public String rcRegnNo;	//MP09CJ7775
		public String taxPaidUpto;	//
		public String rcMakerDesc;	//HYUNDAI MOTORS
		public String rcChasiNo;	//MALAA51HLBM638048B
		public String rcMobileNo;	//
		public String rcRegisteredAt;	//INDORE
		public String rcValidUpto;	//05-07-2026
		public String rcRegnDt;	//06-07-2011
		public String rcFinancer;	//
		public String rcPermanentAddress;	//
		public cls_propertyDetails propertyDetails;
		public cls_taxCalculations[] taxCalculations;
		public cls_penalty penalty;
		public cls_ownerDetails[] ownerDetails;
		public cls_paymentDetails[] paymentDetails;
        public String billNo;	//444010034770
		public String billDueDate;	//11-04-2022
		public String consumerNumber;	//401501528
		public String billAmount;	//Rs. 2380.00
		public String billIssueDate;	//
		public String mobileNumber;	//8158830819
		public String amountPayable;	//Rs. 2380.00
		public String totalAmount;	//Rs. 2380.00
		public String address;	//
		public String consumerName;	//AKTARUL ISLAM
		public String emailAddress;	//
		public String billDate;	//31-03-2022
        public cls_blackListInfo[] blackListInfo;
		//public cls_blackListStatus blackListStatus;
        public string blackListStatus;
		public String bodyTypeDescription;	//SALOON
		public String chassisNumber;	//MBJ11JV40070650241106
		public String color;	//BLACK MET
		public String cubicCapacity;	//1998.0
		public String engineNumber;	//2KD9780094
		public String fatherName;	//TANGAVELU NAYAR
		//public cls_financier financier;
		public string financier;
		public String fitnessUpto;	//17-01-2027
		public String fuelDescription;	//DIESEL
		public String grossVehicleWeight;	//2290
		public String insuranceCompany;	//ROYAL SUNDARAM GENERAL INSURANCE CO. LTD
		public String insurancePolicyNumber;	//VPT0390069000100
		public String insuranceUpto;	//30-01-2023
		public String makerDescription;	//TOYOTA KIRLOSKAR MOTOR PVT LTD
		public String makerModel;	//INNOVA 2.5 G WITH POWER STEER
		public String manufacturedMonthYear;	//11-2006
		public cls_nationalPermitExpiryDate nationalPermitExpiryDate;
		public String nationalPermitIssuedBy;	//1800-01-01
		public String nationalPermitNumber;	//
		//public cls_nocDetails nocDetails;
		public string nocDetails;
        //public cls_nonUseFrom nonUseFrom;
		public string nonUseFrom;
       // public cls_nonUseTo nonUseTo;
		public string nonUseTo;
		public String normsDescription;	//Not Available
		public string numberOfCylinders;
		public String ownerName;	//JAYPRAKASH TANGAVELU NAYAR
		public String ownerSerialNumber;	//3
		public String permanentAddress;	//A/502 5TH FLOOR MANU MAHALI CHS LTD,DNC SCHOOL NANDIVLI ROAD,AYARE DOMBIVALI EAST,421201
		public String presentAddress;	//A/502 5TH FLOOR MANU MAHALI CHS LTD,DNC SCHOOL NANDIVLI ROAD,AYARE DOMBIVALI EAST,421201
		public String pucExpiryDate;	//22-04-2022
		public string pucNumber;
		//public String rcMobileNo;	//
		public string rcNonUseStatus;
		public string rcStatus;
		public String registeredAt;	//KALYAN
		public String registrationDate;	//30-12-2006
		public String registrationNumber;	//MH04CY4545
		public String seatingCapacity;	//7
		public  string sleeperCapacity;
		public string standingCapacity;
		public cls_stateCd stateCd;
		public cls_statePermitExpiryDate statePermitExpiryDate;
		public cls_statePermitIssuedDate statePermitIssuedDate;
		public  string statePermitNumber;
		public string statePermitType;
		public string statusAsOn;
		public string stautsMessage;
		//public String taxPaidUpto;	//2099-12-31
		public String unladenWeight;	//1630
		public String vehicleCatgory;	//LMV
		public String vehicleClassDescription;	//Motor Car(LMV)
		public  string wheelbase;
	}
    public class cls_blackListInfo {
	}
	public class cls_blackListStatus {
	}
	public class cls_financier {
	}
	public class cls_nationalPermitExpiryDate {
	}
	public class cls_nocDetails {
	}
	public class cls_nonUseFrom {
	}
	public class cls_nonUseTo {
	}
	public class cls_numberOfCylinders {
	}
	public class cls_pucNumber {
	}
	public class cls_rcNonUseStatus {
	}
	public class cls_rcStatus {
	}
	public class cls_sleeperCapacity {
	}
	public class cls_standingCapacity {
	}
	public class cls_stateCd {
	}
	public class cls_statePermitExpiryDate {
	}
	public class cls_statePermitIssuedDate {
	}
	public class cls_statePermitNumber {
	}
	public class cls_statePermitType {
	}
	public class cls_statusAsOn {
	}
	public class cls_stautsMessage {
	}
	public class cls_wheelbase {
	}
	public class cls_propertyDetails {
		public String propertyId;	//NX1007310370001
		public String propertyAddress;	//DALICHAND MANJI MEHTA N 6568 (5) PL NO 128  L B S MARG  HOUSE SAI APARTMENT
		public cls_plotAreaInSqYrd plotAreaInSqYrd;
		public cls_plotAreaInSqMtrs plotAreaInSqMtrs;
		public cls_vacantAreaInSqYrd vacantAreaInSqYrd;
		public cls_constructedArea constructedArea;
		public cls_exemptionCategory exemptionCategory;
		public cls_multipurposeOwnership multipurposeOwnership;
		public cls_ownershipType ownershipType;
		public cls_registrationDocNo registrationDocNo;
		public cls_registrationDocDate registrationDocDate;
		public String billingName;	//SUNIL R SHITAPSWATI S SHITAPVIMAL R SHITAP 
		public String billingAddress;	//SAI SIDDHI CHS LTD NEAR DAMODAR PARK L B S MARG GHATKOPAR WEST MUMBAI 400086
		public cls_floorDetails[] floorDetails;
	}
	public class cls_plotAreaInSqYrd {
	}
	public class cls_plotAreaInSqMtrs {
	}
	public class cls_vacantAreaInSqYrd {
	}
	public class cls_constructedArea {
	}
	public class cls_exemptionCategory {
	}
	public class cls_multipurposeOwnership {
	}
	public class cls_ownershipType {
	}
	public class cls_registrationDocNo {
	}
	public class cls_registrationDocDate {
	}
	public class cls_floorDetails {
		public cls_floor floor;
		public cls_areaInSqft areaInSqft;
		public cls_firmName firmName;
		public cls_occupancy occupancy;
		public cls_occupantName occupantName;
		public cls_constructionDate constructionDate;
		public cls_effectiveFromDate effectiveFromDate;
		//public cls_length length;
		public cls_breadth breadth;
	}
	public class cls_floor {
	}
	public class cls_areaInSqft {
	}
	public class cls_firmName {
	}
	public class cls_occupancy {
	}
	public class cls_occupantName {
	}
	public class cls_constructionDate {
	}
	public class cls_effectiveFromDate {
	}
	public class cls_breadth {
	}
	public class cls_taxCalculations {
		public cls_taxType taxType;
		public String totalTax;	//87379
		public String totalTaxDue;	//87379
		public String totalamountPaidRs;	//0
		public cls_paymentStatus paymentStatus;
	}
	public class cls_taxType {
	}
	public class cls_paymentStatus {
	}
	public class cls_penalty {
		public cls_debitAmount debitAmount;
		public cls_creditAmount creditAmount;
		public cls_balanceTaxAmount balanceTaxAmount;
	}
	public class cls_debitAmount {
	}
	public class cls_creditAmount {
	}
	public class cls_balanceTaxAmount {
	}
	public class cls_ownerDetails {
		public String mobileNo;	//9967083333
		public String ownerName;	// SUNIL R SHITAPSWATI S SHITAPVIMAL R SHITAP  
		public cls_gender gender;
		public String email;	//sshitap@gmail.com
		public cls_age age;
		public String panNo;	//ALKPS8237L
		public cls_bankAccountNo bankAccountNo;
	}
	public class cls_gender {
	}
	public class cls_age {
	}
	public class cls_bankAccountNo {
	}
	public class cls_paymentDetails {
		public cls_receiptNo receiptNo;
		public cls_dateOfPayment dateOfPayment;
		public cls_amountPaidRs amountPaidRs;
		public cls_paymentMode paymentMode;
		public cls_valid valid;
		public cls_serialNo serialNo;
	}
	public class cls_receiptNo {
	}
	public class cls_dateOfPayment {
	}
	public class cls_amountPaidRs {
	}
	public class cls_paymentMode {
	}
	public class cls_valid {
	}
	public class cls_serialNo {
	}
	public static KYCWrapper parse(String json){
		return (KYCWrapper) System.JSON.deserialize(json, KYCWrapper.class);
	}

	
}